language: python
#sudo: required
python:
  - "2.7"
 # command to install dependencies
install:
    - pip install codecov
    - pip install -r requirements.txt
    - pip install .
# command to run tests
script:
    - coverage run test.py
after_success:
    - codecov --token=2b8b2285-06b7-48bb-82d9-5487333a90f1
